name: Deploy docs to gh-pages

on:
  push:
    branches: [none]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'    

        # This is needed because we install stripy for litho1pt0 build for documentation
      - name: Install gfortran 
        run: |
          sudo apt-get install -y gfortran

      - name: Install petsc 
        run:  echo ""
         
        # The numpy etc are needed because we install stripy for litho1pt0 build for documentation
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy 
          pip install scipy 
          pip install Cython
          pip install sympy
          pip install pint
          pip install stripy
          pip install pdoc3
   
      - name: Build docs with pdoc
        run: | 
          mkdir -p docs
          pdoc --config latex_math=True --html -o docs --force quagmire 

      # Note deploy key needs the ----BEGIN ... KEY---- lines too
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_PR_KEY }}
          publish_dir: docs/quagmire