name: conda -c underworldcode 

on: 
  release:
    types: [created, edited]
  push:
    branches:
      - dev

# Limited to ubuntu and macos because of petsc / petsc4py
# py27 seems problematic in stripy builds

jobs:
  catch_and_release: 
    name: ${{matrix.os}} build and test on py (${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [  'ubuntu-latest', 'macos-latest']
        python-version: [ '3.7']

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Install dependencies with conda
        shell: bash -l {0}
        run: |
          conda install conda-build anaconda-client 
          conda install -c conda-forge compilers numpy scipy sympy
          conda install -c conda-forge petsc4py petsc mpi4py h5py
          conda install -c conda-forge pint 
          conda install -c underworldcode stripy 
          conda install pytest

          conda config --add channels underworldcode
          conda config --add channels conda-forge


      - name: Reinvent the wheel / upload (UBUNTU)
        if: matrix.os == 'ubuntu-latest' 

        env:
          ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME}}
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD}}

        shell: bash -l {0}
        run: |
          # Conda version

          anaconda logout
          printf Y | anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PASSWORD --hostname quagy-virtual-${{ matrix.os}}-${{ matrix.python-version }}
          python setup.py bdist_conda   # this will upload to lmoresi in the first instance ... 
          anaconda upload -u underworldcode --skip-existing /usr/share/miniconda/envs/test/conda-bld/*/*.tar.bz2 
          anaconda logout

          
      - name: Reinvent the wheel / upload (MACOS)
        if: matrix.os == 'macos-latest' 

        env:
          ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME}}
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD}}

        shell: bash -l {0}
        run: |
          # Conda version

          anaconda logout
          printf Y | anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PASSWORD --hostname quagy-virtual-${{ matrix.os}}-${{ matrix.python-version }}
          python setup.py bdist_conda   # this will upload to lmoresi in the first instance ... 
          anaconda upload -u underworldcode --skip-existing /usr/local/miniconda/envs/test/conda-bld/*/*.tar.bz2 
          anaconda logout

         


